# Generated by Django 6.0.6 on 2026-07-01 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do produto.', max_length=200, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)')),
                ('quantidade_atual', models.IntegerField(default=0, help_text='Saldo atual em estoque. Atualizado automaticamente pelas movimentações.', verbose_name='Quantidade Atual')),
                ('quantidade_minima', models.IntegerField(default=0, help_text='Quantidade mínima em estoque. Abaixo disso o sistema emitirá alerta.', verbose_name='Quantidade Mínima')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para desativar o produto sem excluí-lo.', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='categorias.categoria', verbose_name='Categoria')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='fornecedores.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produtos_produto',
                'ordering': ['nome'],
            },
        ),
    ]
