# Generated by Django 6.0.6 on 2026-07-01 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], help_text='Entrada aumenta o estoque. Saída diminui o estoque.', max_length=10, verbose_name='Tipo')),
                ('quantidade', models.PositiveIntegerField(help_text='Quantidade movimentada. Deve ser maior que zero.', verbose_name='Quantidade')),
                ('observacao', models.TextField(blank=True, default='', help_text='Observação opcional sobre a movimentação.', verbose_name='Observação')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='produtos.produto', verbose_name='Produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'db_table': 'movimentacoes_movimentacao',
                'ordering': ['-data'],
            },
        ),
    ]
