# Generated by Django 6.0.6 on 2026-07-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Razão social ou nome fantasia do fornecedor.', max_length=200, verbose_name='Nome / Razão Social')),
                ('cnpj', models.CharField(help_text='CNPJ no formato 00.000.000/0000-00.', max_length=18, unique=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, default='', help_text='Telefone de contato com DDD.', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='E-mail de contato do fornecedor.', max_length=254, unique=True, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para desativar o fornecedor sem excluí-lo.', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'db_table': 'fornecedores_fornecedor',
                'ordering': ['nome'],
            },
        ),
    ]
